### PR TITLE
Final website update

### PR DESCRIPTION
**Pull request by strongs**

### CODE REVIEW

**Comment by jayfo** [comment]
This needs rebased onto `master`. There's also a conflict that can't be merged.

Look at the network graph and see how you're based on a very old commit:

https://github.com/uwcse440/web-cse440-au15/network

So you need to ensure your master is current:

```
git checkout master
git pull uwcse440 master
git push
```

Then you need to rebase onto it, probably resolving conflicts along the way:

```
git checkout MiPhoneFinal
git rebase -i master
git push -f
```

That'll update this.

**Comment by jayfo** [comment]
I looked at this to attempt to get it merged, but you've got merge conflicts in here where I have no way to determine which version you want / need. I think the fundamental issue is that you started with an old base for your feature branch.

If you have a directory that contains your current site, you might be better off with the old copy-paste into a new feature branch based on the current master, rather than trying to fix this pull.

But you need to get this merged.  CCing @fiannaca in case he has any ideas.

**Comment by fiannaca** [comment]
@strongs I will start fresh just like we did when you came to my office:

Update your master:

```
git checkout master
git pull uwcse440 master
git push
```

Create a new branch:

```
git checkout -b MyNewBranchName
```

Copy all of your website files into the '_projects/MiPhone/' directory and commit them:

```
git add --all
git commit -m 'Updating the MiPhone website'
```

Push the new branch:

```
git push origin MyNewBranchName
```

And then finally create the pull request from GitHub.

**Comment by jayfo** [comment]
I cherry-picked this into #190.

I resolved the conflicts by assuming you wanted the text in this branch instead of the current `master`.

If you'll submit more work, delete this feature branch. Start a new one from the current `master` before doing any additional work.

**Pull request closed without merging**
