### PR TITLE
Add missing images and files

### PR DESCRIPTION
**Pull request by andrewtat**

### CODE REVIEW

**Comment by jayfo** [comment]
Can you rebase this onto `master`?

It'd merge fine, just good habit.

**Comment by jayfo** [comment]
```
git checkout master
git pull uwcse440 master
git push

git checkout neat-feature
git rebase master
git push -f
```

**Comment by jayfo** [comment]
@andrewtat Still waiting for a rebase.  :)

**Comment by andrewtat** [comment]
@jayfo Sorry for not pushing the rebase. I'm still getting used to the rebase action :/

**Comment by jayfo** [comment]
@andrewtat 

So I could clean this up (see #142), but I want you to. And I'm curious if these commands work.

Look at the network graph:

https://github.com/uwcse440/web-cse440-au15/network

You have your own `master`, that's not good. Your feature is pointing there too. So first let's get your `master` back where it belongs.

```
git checkout master
git reset --hard uwcse440/master
git push -f
```

Check the graph, your `master` tag should be gone, meaning your back to using the actual `master`.

Now do the rebase again:

```
git checkout near-feature
git rebase master
git push -f
```

See if that gets you a clean feature branch, like I have in #142?

**Comment by jayfo** [comment]
@andrewtat 

You need to get this cleaned up and merged.

**Comment by andrewtat** [comment]
I think I rebased correctly? There was one point where I had to `git rebase --skip` but from the commit logs, everything seems to match.

**Pull request merged**
