### PR TITLE
Miphone patch 1

### PR DESCRIPTION
**Pull request by sierraa**

### CODE REVIEW

**Comment by jayfo** [comment]
You've got some conflicts in here and will need to resolve those. Easiest way is to rebase this feature branch onto the current `master`.

```
git checkout master
git pull uwcse440 master
git push

git checkout miphone-patch-1
git rebase -i master
git push -f
```

It'll update this pull request.

**Comment by jayfo** [comment]
@sierraa This still needs resolved.  :)

**Comment by sierraa** [comment]
@jayfo Is there a way to rebase from the Github website? I submitted my pull request from the browser without cloning the repo to my machine...

**Comment by jayfo** [comment]
I am cleaning this up in #136, and will merge. But I cannot do that in general.

You / your group will need to get comfortable with git as part of finalizing your website.

**Pull request closed without merging**
