### PR TITLE
Timeout

### PR DESCRIPTION
**Pull request by jdaum**
small changes made to the website

### CODE REVIEW

**Comment by jayfo** [comment]
Instead of pulling master into your feature branch, rebase onto it:

```
git checkout timeout
git rebase -i master
git push -f
```

**Comment by jdaum** [comment]
Are these commits supposed to appear here? I don't think that happened before....

**Comment by jayfo** [comment]
It looks like your `master` is behind, causing this issue:

You need to update your `master`:

```
git checkout master
git pull uwcse440 master
git push
```

Then rebase your branch, and resolve any conflicts while you're at it:

```
git checkout timeout
git rebase -i master
git push -f
```

That'll update this pull request.

**Comment by jayfo** [comment]
Hmmm, we might be in strange git land.

**Comment by jdaum** [comment]
Ok, it looks better now on the network graph. So I hope it worked.

**Comment by jayfo** [comment]
Looks great now.

**Pull request merged**
