### PR TITLE
Poliscope

### PR DESCRIPTION
**Pull request by jgao26**
pull request from feature branch?

### CODE REVIEW

**Comment by jayfo** [comment]
Check out the network graph:

https://github.com/uwcse440/web-cse440-au15/network

download 1

You have you own `master`. That's bad. You want to get your `master` back to the `master`. Your already have a feature branch `poliscope` that will "hold your place" with the work you've done:

```
git checkout master
git reset --hard uwcse440/master
git push -f
```

Given that your feature branch is already coming off our current `master`, I think that's all you need to do. This branch should merge fine, but you'll have trouble later if you don't fix your `master`.

**Comment by jayfo** [comment]
Looks like your `master` rejoined when I merged.

download 2

**Comment by jgao26** [comment]
I'm confused, I think I fixed the issue of the master branch on my computer but when I paste the files into the folder for the feature branch none of the changes are being registered I think because the files are the same from the merge?

but looking at the poliscope website from the projects page of the cse440 website it looks messed up and like a combination of the initial website and the one I'm trying to submit

Is there a way to remove all the files from the poliscope folder so I can make a new clone and try committing again? (I assume this is the problem but I'm not very familiar with github)

**Comment by jgao26** [comment]
I think I finished the issue of the master branch on my computer, but looking at the cse440 projects page for poliscope our site now looks like a combination of the initial website and the reworked one I'm trying to push.  Is that because of the merge earlier and it didn't cleanly combine the code, or does this mean our site just isn't working?

**Comment by jgao26** [comment]
fixed the issue*

**Comment by jayfo** [comment]
The pull you sent (this one), is now merged.

Did you refresh your browser, in case it's caching your CSS?

Without knowing what's "missing", I'm not sure what else to say here. Nothing I can see says things failed to merge. Your pull seemed fine. If something got overwritten, it would have been on your machine when your master was ahead. But I'm not sure how, especially since your files are separated from everybody else's (i.e., in your directory).

**Pull request merged**
