### PR TITLE
Timeout

### PR DESCRIPTION
**Pull request by jdaum**
I hope it is correct this time. :)

### CODE REVIEW

**Comment by jayfo** [comment]
You've somehow got two commits that both include the image change:

https://github.com/jdaum/web-cse440-au15/commit/dc95e6264eb414132105a8dcbc78eeca0657f46f

https://github.com/jdaum/web-cse440-au15/commit/69d3bcf374c16a242b54a4c005cdbc09374b43c9

From looking at the network graph:

https://github.com/uwcse440/web-cse440-au15/network

What's happening is that you still have that first commit on your `master`. See how your node labeled `master` is not the same as `uwcse440:master`. So we want to reset that:

```
git checkout master
git reset --hard uwcse440/master
git push -f
```

Then you want to rebase your feature branch:

```
git checkout timeout
git rebase master
git push -f
```

That should update this pull request, since you're already pointed at `jdaum:timeout`. No need to close this and create a new one.

**Comment by jdaum** [comment]
Thank you for your help!
I did the reset, so I hope it works now. 
Sorry for the trouble, it has been a while since I last used git. :)

**Comment by jayfo** [comment]
It looks in the network viewer like your `master` is now back with the primary `master`. But you've still got two identical commits, each putting in your image. We could merge this, but let's clean it up?

I think you want to squash those two commits into one:

```
git checkout timeout
git rebase -i master
```

It'll prompt you with the two commits. Do a little reading on squashing / rebasing, you'll see that you can change the second commit to a squash. You'll then get a chance to edit a combined commit message. When you're done, you'll need to push again:

```
git push -f
```

As before, this will update your feature branch for this pull.

**Comment by jdaum** [comment]
Ok, I think there is only one commit now. Learned something new. :)
For future pull requests, I just work on the timeout path and send a pull requests at the end for the assignment? 
Thanks again!

**Comment by jayfo** [comment]
This one looks right, I'll merge now.

After this is merged, the pull request is done. Your edits become part of `uwcse440:master`. So at the point you can delete your feature branch and update `jdaum:master` by pulling from `uwcse440:master`.

Then you'd create a new feature branch that you use to submit future changes. If you have deleted `timeout`, you can re-use that name.

**Pull request merged**
