### PR TITLE
add a thumbnail

### PR DESCRIPTION
**Pull request by chiahan**

### CODE REVIEW

**Comment by jayfo** [comment]
This feature branch is based off your prior commit, rather than our current `master`.

https://github.com/uwcse440/web-cse440-au15/network

You want to ensure your `master` is current, then rebase onto it.

```
git checkout master
git pull uwcse440 master
git push
git checkout schoolview-feature
git rebase master
git push -f
```

That'll update this pull request, since the request points at `schoolview-feature`.

**Comment by jayfo** [comment]
Looking at the current network graph, I think you pulled our `master` into your feature branch.

network

See how there are other pull requests submitted to me that cleanly come from the current master, where yours goes back further and has the additional merge lines in it.

The command sequence I gave above should fix this.

**Comment by jayfo** [comment]
@chiahan Still waiting for you to clean these up so we can merge.  :)

**Comment by chiahan** [comment]
I'm done! thank you so much!

**Comment by jayfo** [comment]
Your master is still way behind ours, and you've still got a merge in there. It looks like you're pulling our master into your branch, rather than into your master. And it looks like your master is a bit out-of-sync.

download

Try getting your master reset to ours:

```
git checkout master
git reset --hard uwcse440/master
git pull uwcse440 master
git push -f
```

Then the rebase again:

```
git checkout schoolview-feature
git rebase -i master
git push -f
```

**Comment by chiahan** [comment]
I do these steps again, is it work now@@?

**Comment by jayfo** [comment]
Yay!

**Pull request merged**
