### PR TITLE
Ecotopia

### PR DESCRIPTION
**Pull request by jskang16**
Adding boostrap template starter code

### CODE REVIEW

**Comment by jayfo** [comment]
From the network graph, you can see this branch is based off a commit from your prior feature branch:

https://github.com/uwcse440/web-cse440-au15/network

It's "cleaner" to rebase it onto the current `master`.

Want to do that?

**Comment by jskang16** [comment]
Hmm...
Would that mean I should do something like:
[commit onto local branch]
git rebase -i master
[squash commits down to one]
git push -u origin <branch name>

?

**Comment by jayfo** [comment]
Yes, I think it's approximately:

Ensure your `master` is current:

```
git checkout master
git pull uwcse440 master
git push
```

Rebase your branch onto `master`, deciding whether you want to squash your commits:

```
git checkout ecotopia
git rebase -i master
git push -f
```

That'll push to `jskang16:ecotopia`, which is where this pull request is pointed. So it'll update this request.

**Comment by jskang16** [comment]
Ok -- I followed the instructions here:
https://help.github.com/articles/syncing-a-fork/
to sync since "git pull uwcse400 master" didn't work. But thanks for the help! Let me know if it's still not quite right.

**Comment by jayfo** [comment]
Looks good, thanks.

**Pull request merged**
