### PR TITLE
Updating the MiPhone website

### PR DESCRIPTION
**Pull request by fiannaca**

### CODE REVIEW

**Comment by fiannaca** [comment]
Did this with Scott to show him how to use Git.

**Comment by fiannaca** [comment]
@jayfo Shouldn't there be two checks from travis-ci? This is only showing 1

**Comment by jayfo** [comment]
No this looks right to me.

**Comment by jayfo** [comment]
So is this ready to merge? Or is Scott going to do from his account?

**Comment by fiannaca** [comment]
This is ready to merge. He is going to repeat the process to add his video.

**Pull request merged**
